### ISSUE TITLE
subprocess.CalledProcessError: Command '['./ninja', '-v']' returned non-zero exit status 1. ERROR: tools/ninja failed to build.

### ISSUE THREAD

**Issue by Bpc-CPU** [hugcabbage/shared-lede#31]
Traceback (most recent call last):
  File "/home/runner/work/shared-lede/shared-lede/build_dir/host/ninja-1.11.1/configure.py", line 725, in <module>
    subprocess.check_call(rebuild_args)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./ninja', '-v']' returned non-zero exit status 1.
make[3]: *** [Makefile:40: /home/runner/work/shared-lede/shared-lede/build_dir/host/ninja-1.11.1/.built] Error 1
make[3]: Leaving directory '/home/runner/work/shared-lede/shared-lede/tools/ninja'
time: tools/ninja/compile#22.17#2.41#23.82
    ERROR: tools/ninja failed to build.

Hi. how can I fix it？
大佬我怎么修复这个报错呢？

**Comment by Bpc-CPU** [comment]
我升级了g++导致的。。。
